### ISSUE TITLE
Warning: LastPass deprecation

### ISSUE THREAD

**Issue by monikered** [bluelabsio/db-facts#38]
This repository contains dependencies on LastPass, which is scheduled for deprecation on 8/21/23. Workflows that continue to use this library may fail until a 1Password integration patch is released. 

**To continue using this library in the meantime, you must download [this LastPass-to-1Password utility](https://github.com/bluelabsio/lpass2op/) and follow the instructions in the readme.** 

If this does not work at first, make sure that _every_ field from any LastPass entry referenced by this library has been successfully migrated into 1Password. Some users have found that fields such as URL, Hostname, Database, or Port need to be manually copied over.

If you need any assistance, please reach out to us in #help.

**Comment by monikered** [comment]
References to LastPass in this library can be found here: https://github.com/search?q=repo%3Abluelabsio%2Fdb-facts%20lastpass&type=code

**Comment by Brunope** [comment]
The hard part about this is gonna be actually releasing a new version to users. Do you have a plan for this @monikered ? There is an old homebrew formula that sure doesn't work anymore, as well as the version published on pypi. Since db-facts is a dependency of records-mover, the important thing is to make it so updating records-mover will update db-facts as well.

**Comment by Brunope** [comment]
Also, it is my understanding that db-facts isn't something we plan on supporting for much longer, so a quick and dirty solution is acceptable here. Is this accurate?

**Comment by monikered** [comment]
Hey @Brunope! There is not yet a plan for releasing this to users -- let's meet and discuss options. And yes, quick and dirty is what we're after.

**Comment by naswierczek** [comment]
I'm not sure if there's a plan to remove db-facts or not but I can say that db-facts is heavily used and the fact that it lacks 1password support is a long-pole in finishing this migration and getting lastpass completely out of our processes.

I'm thinking I have to at least address this for records-mover, because it relies on db-facts to get secrets from lastpass. This probably means adding 1pass support to db-facts.

**Comment by Brunope** [comment]
@naswierczek some important context. db-facts isn't really functional on its own. it actually requires a bunch of configuration files that specify all the info for the various dbs it connects to. Since db-facts is open source, these files are provided in a separate private package called `bluelabs-db-facts`. On my machine this file exists at `/usr/local/etc/dbfacts.yml`. In this file it specifies where the credentials for each database should be pulled from, with many of them specifying lastpass.

Example:

```
  redshift:
    jinja_context_name: redshift
    exports_from: lpass
    lastpass_entry: Redshift - Bluelabs
    exports:
      lastpass_share_name_suffix: blue labs redshift
      'redshift_spectrum_base_url_{{ schema }}_spectrum': s3://bluelabs-redshift-spectrum/
```

db-facts does some weird jinja templating that I don't understand exactly but eventually after looking up the database in this config it calls into `lpass.py::db_info_from_lpass`.

My quick and dirty solution is to edit the functions in `lpass.py` to actually use 1password instead.

A more elegant solution might change the config file itself to specify a new type of export, "1password" for instance, and branch the logic higher up in db-facts and call into a `1password.py` rather than `lpass.py`.

Hope this made sense, let me know your thoughts.
